import { StyleSheet } from "react-native";
import colors from "./colors";

// TODO: butonların yaptığı gereksiz bir kalabalık var düzeltilmeli belki buton componenti yaparak

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  centeredView: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    padding: 12,
  },
  outlinedWhiteContainer: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primary,
    padding: 12,
  },
  textinput: {
    marginTop: 14,
    color: colors.primary,
    fontSize: 17,
    borderColor: colors.primary,
    width: 245,
    height: 40,
    borderWidth: 2,
    padding: 10,
    borderRadius: 2,
    backgroundColor: colors.white,
  },
  loginbutton: {
    padding: 8,
    backgroundColor: colors.primary,
    marginTop: 14,
    width: 245,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 2,
    height: 40,
  },
  registerbutton: {
    padding: 8,
    backgroundColor: colors.important,
    marginTop: 14,
    width: 245,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 2,
    height: 40,
  },
  tabtitle: {
    fontSize: 33,
    marginLeft: 20,
    marginTop: 36,
    color: colors.primary,
  },
  uploadnewbutton: {
    padding: 8,
    backgroundColor: colors.positive,
    marginTop: 8,
    width: 312,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 2,
    height: 40,
    alignSelf: "center",
  },
  cancelbutton: {
    padding: 8,
    backgroundColor: colors.negative,
    marginTop: 9,
    width: 292,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 2,
    height: 40,
    alignSelf: "center",
  },
  okaybutton: {
    padding: 8,
    backgroundColor: colors.positive,
    marginTop: 9,
    width: 292,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 2,
    height: 40,
    alignSelf: "center",
  },
  imagebox: {
    width: 100,
    height: 100,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.primary,
    margin: 3,
  },
  likescontainer: {
    position: "absolute",
    alignSelf: "flex-end",
    flexDirection: "row",
    backgroundColor: "rgba(0, 0,0, 0.5)",
    padding: 2,
    alignContent: "center",
    bottom: 0,
    alignItems: "center",
  },
});
